name: Build and Publish Docs

on:
  workflow_call:
    inputs:
      project_type:
        description: The type of project: 'typescript' or 'python'
        required: true
        type: string

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build Typedoc Documentation
        if: ${{ inputs.project_type == 'typescript' }}
        uses: p2arthur/algokit-shared-config-forked/.github/actions/generate-typescript-docs@main

      - name: Build Sphinx Documentation
        if: ${{ inputs.project_type == 'python' }}
        uses: p2arthur/algokit-shared-config-forked/.github/actions/generate-python-docs@main

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages-docs
          path: ${{ inputs.project_type == 'python' && 'docs/_build/html' || 'docs/_html' }}
          retention-days: 1

  publish-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - name: Download Documentation Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages-docs
          path: docs/downloaded

      - name: Deploy Documentation
        uses: p2arthur/algokit-shared-config-forked/.github/actions/publish-docs@main
        with:
          artifact_path: docs/downloaded

      - name: Publish to Dev portal
        uses: p2arthur/algokit-shared-config-forked/.github/actions/devportal-publish-docs@main
        with:
          github_token: ${{ secrets.GH_TOKEN }}
