name: Build and Publish Docs

on:
  workflow_call:
    inputs:
      project_type:
        description: "The type of project: 'typescript' or 'python'"
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

permissions:
  contents: write # Needed if publishing to a branch
  pages: write
  id-token: write

jobs:
  build-and-prep:
    runs-on: ubuntu-latest
    env:
      # Standardize the build output location for the entire job
      DOCS_OUTPUT: "docs_dist"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Typedoc Documentation
        if: ${{ inputs.project_type == 'typescript' }}
        uses: p2arthur/algokit-shared-config-forked/.github/actions/generate-typescript-docs@main
        # Ensure this action outputs to ${{ env.DOCS_OUTPUT }}

      - name: Build Sphinx Documentation
        if: ${{ inputs.project_type == 'python' }}
        uses: p2arthur/algokit-shared-config-forked/.github/actions/generate-python-docs@main
        # Ensure this action outputs to ${{ env.DOCS_OUTPUT }}

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-bundle
          path: ${{ env.DOCS_OUTPUT }}
          retention-days: 1

  publish:
    needs: build-and-prep
    runs-on: ubuntu-latest
    steps:
      - name: Download Documentation Artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-bundle
          path: site-content

      - name: Deploy to GitHub Pages
        uses: p2arthur/algokit-shared-config-forked/.github/actions/publish-docs@main
        with:
          artifact_path: site-content

      - name: Publish to Algorand DevPortal
        uses: p2arthur/algokit-shared-config-forked/.github/actions/devportal-publish-docs@main
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          docs_path: site-content
