name: CI TypeScript
on:
  workflow_call:

jobs:
  node-ci:
    name: CI Check # Indented 2 spaces
    runs-on: ubuntu-latest # Indented 2 spaces
    steps: # Indented 2 spaces
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Node CI Action
        uses: p2arthur/algokit-shared-config-forked/.github/actions/node-ci@main
        with:
          working-directory: "."
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  build:
    name: Build and Zip Package
    needs: node-ci
    uses: p2arthur/algokit-shared-config-forked/.github/workflows/node-build-zip.yml@main
    with:
      node-version: 20.x
      build-path: dist
      artifact-name: package
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-check-publish-docs:
    needs: node-ci
    name: Build, Check and Publish Docs
    uses: p2arthur/algokit-shared-config-forked/.github/workflows/build-and-publish-docs.yml@main
    with:
      project_type: "typescript"
    secrets: inherit # Added to ensure docs build has access to tokens if needed
