name: Prod Publish

on:
  workflow_call:
    secrets:
      BOT_ID:
        required: true
      BOT_SK:
        required: true

jobs:
  prod_release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate bot token
        uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_SK }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app_token.outputs.token }}

      - name: Sync Branches
        env:
          GH_TOKEN: ${{ steps.app_token.outputs.token }}
        run: |
          # 1. Update the 'release' branch using 'main' as the source
          # We use the full git syntax here because 'gh repo sync' 
          # is designed mostly for syncing forks to upstreams.

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Fetch all branches to ensure we see 'main' and 'release'
          git fetch origin main release

          # Switch to release and merge main
          git checkout release
          git merge origin/main --no-edit
          git push origin release

          # Switch back to main and ensure it's in sync
          git checkout main
          git merge origin/release --no-edit
          git push origin main
        shell: bash
