name: On Merge to Main

on:
  workflow_call:
    inputs:
      project_type:
        required: true
        type: string # 'typescript' or 'python'
    secrets:
      NPM_TOKEN:
        required: false
      GH_TOKEN:
        required: true
      BOT_ID:
        required: true
      BOT_SK:
        required: true

jobs:
  # --- Dispatch to TypeScript Workflow ---
  typescript-ci:
    if: ${{ inputs.project_type == 'typescript' }}
    uses: ./.github/workflows/ci-typescript.yml
    secrets: inherit

  # --- Dispatch to Python Workflow ---
  python-ci:
    if: ${{ inputs.project_type == 'python' }}
    uses: ./.github/workflows/ci-python.yml
    secrets: inherit

  # --- Common Release Job ---
  release:
    name: Release Package
    needs: [typescript-ci, python-ci]
    if: always() && !cancelled() && !contains(needs.*.result, 'failure')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Generate Bot Token
        id: get_token
        uses: p2arthur/algokit-shared-config/.github/actions/generate-bot-token@main
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_SK }}

      - name: Run Semantic Release
        uses: p2arthur/algokit-shared-config/.github/actions/release-package@main
        with:
          BOT_TOKEN: ${{ steps.get_token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
