name: Prod Publish

on:
  workflow_call:
    secrets:
      BOT_ID:
        required: true
      BOT_SK:
        required: true

jobs:
  prod_release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate bot token
        uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_SK }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app_token.outputs.token }}

      - name: Sync and Push
        run: |
          # Automatically set identity based on the App's info
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Sync 'release' branch
          git checkout release
          git pull origin release --rebase # Ensure we have latest
          git merge origin/main --no-edit
          git push origin release

          # Sync 'main' branch
          git checkout main
          git merge origin/release --no-edit
          git push origin main
        shell: bash
