name: On Merge to Main

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        description: Custom NPM auth token for private package access.
        required: true
      GH_TOKEN:
        description: GitHub token required for checkout and GitHub package access.
        required: true
      BOT_TOKEN:
        description: The Bot Token for committing changes back to the repository.
        required: true
jobs:
  ci:
    name: Fake CI Check
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI for testing downstream jobs
        run: echo "Skipping actual CI checks for now to test build and release sequence."

  build:
    name: Build and Zip Package
    needs: ci
    uses: algorandfoundation/algokit-shared-config/.github/workflows/node-build-zip.yml@pr/release-workflow
    with:
      node-version: 20.x
      build-path: dist
      artifact-name: package
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  check_docs:
    needs: ci
    name: Check docs are up to date
    uses: algorandfoundation/algokit-shared-config/.github/workflows/check-docs.yml@pr/release-workflow

  generate-publish-docs:
    needs: check_docs
    name: Publish docs
    uses: algorandfoundation/algokit-shared-config/.github/workflows/build-and-publish-docs.yml@pr/release-workflow

  release:
    name: Release Package
    needs: [ci, build, check_docs, generate-publish-docs]
    uses: algorandfoundation/algokit-shared-config/.github/workflows/release-package.yml@pr/release-workflow
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
