name: On Merge to Main

on:
  workflow_call:
    inputs:
      project_type:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: false
      GH_TOKEN:
        required: true
      BOT_ID:
        required: true
      BOT_SK:
        required: true

jobs:
  typescript-ci:
    if: ${{ inputs.project_type == 'typescript' }}
    # USE ABSOLUTE PATHS FOR NESTED CALLS
    uses: p2arthur/algokit-shared-config-forked/.github/workflows/ci-typescript.yml@main
    secrets: inherit

  python-ci:
    if: ${{ inputs.project_type == 'python' }}
    uses: p2arthur/algokit-shared-config-forked/.github/workflows/ci-python.yml@main
    secrets: inherit

  release:
    name: Release Package
    needs: [typescript-ci, python-ci]
    # This logic ensures release runs if the active CI job succeeded OR if the other was skipped
    if: |
      always() && 
      (needs.typescript-ci.result == 'success' || needs.typescript-ci.result == 'skipped') &&
      (needs.python-ci.result == 'success' || needs.python-ci.result == 'skipped') &&
      !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Generate Bot Token
        id: get_token
        uses: p2arthur/algokit-shared-config-forked/.github/actions/generate-bot-token@main
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_SK }}

      - name: Run Semantic Release
        uses: p2arthur/algokit-shared-config-forked/.github/actions/release-package@main
        with:
          BOT_TOKEN: ${{ steps.get_token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
