name: Prod Publish

on:
  workflow_call:
    secrets:
      BOT_ID:
        required: true
      BOT_SK:
        required: true

jobs:
  prod_release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate bot token
        uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_SK }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app_token.outputs.token }}

      - name: Sync Branches
        run: |
          # Configure identity
          git config user.email "179917785+engineering-ci[bot]@users.noreply.github.com"
          git config user.name "engineering-ci[bot]"

          # 1. Update 'release' to match 'main'
          git checkout release
          git merge origin/main --ff-only || git merge origin/main --no-edit
          git push origin release

          # 2. Ensure 'main' has any changes from 'release' (like tags/metadata)
          git checkout main
          git merge origin/release --no-edit
          git push origin main
        shell: bash
